/**
 * NSD (Narrative Scene Document) Type Definitions
 *
 * Domain types for NSD document upload, parsing, and validation.
 * These types are framework-agnostic and can be used in any layer.
 *
 * @module domain/types
 */

// ============================================================================
// NSD Upload Request/Response Types
// ============================================================================

/**
 * Request payload for uploading an NSD document.
 *
 * Supports two source types: file path (for Electron main process) or
 * direct text content (for paste scenarios). Exactly one source must be provided.
 *
 * @example
 * // File path upload (from file dialog)
 * const request: NSDUploadRequest = {
 *   source: { path: '/Users/dev/project/docs/quest-01.md' },
 *   correlationId: '550e8400-e29b-41d4-a716-446655440000'
 * };
 *
 * @example
 * // Direct text upload (from paste)
 * const request: NSDUploadRequest = {
 *   source: { text: '# Quest 01: The Tavern Contract\n\n## Scene 1: Meeting...' },
 *   correlationId: '550e8400-e29b-41d4-a716-446655440000'
 * };
 */
export type NSDUploadRequest = {
  /**
   * Source of the NSD document content.
   *
   * Must provide exactly one of:
   * - `path`: Absolute file system path to the markdown file (main process)
   * - `text`: Direct markdown text content (paste scenario)
   *
   * @example
   * { path: '/path/to/quest.md' }
   * @example
   * { text: '# Quest Title\n\nScene content...' }
   */
  source: {
    /** Absolute file path to the NSD markdown file (optional) */
    path?: string;
    /** Direct markdown text content (optional) */
    text?: string;
  };

  /**
   * Unique correlation identifier for this upload operation.
   *
   * Used to track progress events and match responses to requests.
   * Should be a UUID v4 or similar unique identifier.
   *
   * @example
   * '550e8400-e29b-41d4-a716-446655440000'
   */
  correlationId: string;
};

/**
 * Response payload returned after successful NSD document upload and parsing.
 *
 * Contains the document ID, extracted scene list, and any warnings generated
 * during the parsing process.
 *
 * @example
 * const response: NSDUploadResponse = {
 *   documentId: 'nsd-doc-123',
 *   sceneList: [
 *     { id: 'scene-1', title: 'Tavern Contract', sceneNumber: 1, ... },
 *     { id: 'scene-2', title: 'Bard Conversation', sceneNumber: 2, ... }
 *   ],
 *   warnings: ['Some dialogue lines lack speaker attribution']
 * };
 */
export type NSDUploadResponse = {
  /**
   * Unique identifier for the uploaded NSD document.
   *
   * Generated by the system and used to reference this document
   * in subsequent operations (scene selection, prompt generation).
   *
   * @example
   * 'nsd-doc-123'
   * @example
   * 'quest-01-tavern-contract'
   */
  documentId: string;

  /**
   * List of scenes extracted from the NSD document.
   *
   * Each scene represents a narrative unit with title, content,
   * and optional summary. Scenes are ordered by appearance in the document.
   *
   * @example
   * [
   *   { id: 'scene-1', title: 'Tavern Contract', sceneNumber: 1, content: '...', summary: '...' },
   *   { id: 'scene-2', title: 'Bard Conversation', sceneNumber: 2, content: '...' }
   * ]
   */
  sceneList: NSDSceneDTO[];

  /**
   * Optional list of non-critical warnings from parsing.
   *
   * Warnings indicate issues that didn't prevent parsing but may
   * affect quality (missing metadata, formatting issues, etc.).
   *
   * @example
   * ['Scene 3 lacks summary', 'Inconsistent scene numbering detected']
   */
  warnings?: string[];
};

/**
 * Progress update for NSD document upload operations.
 *
 * Emitted periodically during upload to keep the UI informed of
 * the current processing stage and completion percentage.
 *
 * @example
 * const progress: NSDUploadProgress = {
 *   stage: 'parsing',
 *   percent: 45,
 *   correlationId: '550e8400-e29b-41d4-a716-446655440000'
 * };
 */
export type NSDUploadProgress = {
  /**
   * Current stage of the upload process.
   *
   * Stages progress sequentially: reading → parsing → extracting → validating → complete.
   * Each stage represents a distinct phase of document processing.
   *
   * - `reading`: Reading file from disk or receiving text content
   * - `parsing`: Parsing markdown structure and extracting sections
   * - `extracting`: Identifying and extracting individual scenes
   * - `validating`: Validating document structure and required fields
   * - `complete`: All processing finished successfully
   *
   * @example
   * 'parsing'
   */
  stage: NSDUploadStage;

  /**
   * Completion percentage for the current stage (0-100).
   *
   * Indicates progress within the current stage. When `stage` is 'complete',
   * this value should be 100.
   *
   * @example
   * 45 (45% complete)
   */
  percent: number;

  /**
   * Correlation ID matching the original upload request.
   *
   * Links this progress update to the specific upload operation
   * for proper UI tracking.
   *
   * @example
   * '550e8400-e29b-41d4-a716-446655440000'
   */
  correlationId: string;
};

/**
 * Error response for failed NSD document upload operations.
 *
 * Provides structured error information with error code, message,
   and correlation ID for debugging and user feedback.
 *
 * @example
 * const error: NSDUploadError = {
 *   code: 'NSD_PARSE_ERROR',
 *   message: 'Failed to extract scenes: Invalid markdown format',
 *   correlationId: '550e8400-e29b-41d4-a716-446655440000'
 * };
 */
export type NSDUploadError = {
  /**
   * Machine-readable error code for categorization.
   *
   * Standard error codes:
   * - `NSD_READ_ERROR`: Failed to read file or text content
   * - `NSD_PARSE_ERROR`: Markdown parsing failed
   * - `NSD_VALIDATE_ERROR`: Document validation failed
   * - `NSD_EXTRACT_ERROR`: Scene extraction failed
   * - `NSD_SIZE_ERROR`: File exceeds maximum size (1MB)
   * - `NSD_EMPTY_ERROR`: Document is empty or contains no content
   *
   * @example
   * 'NSD_PARSE_ERROR'
   * @example
   * 'NSD_SIZE_ERROR'
   */
  code: string;

  /**
   * Human-readable error message for display.
   *
   * Should provide clear, actionable information about what went wrong
   * and how to fix it. Avoid technical jargon when possible.
   *
   * @example
   * 'Failed to parse NSD document: Invalid markdown format in scene 2'
   * @example
   * 'File size exceeds 1MB limit. Please split your document into smaller files.'
   */
  message: string;

  /**
   * Correlation ID matching the failed upload request.
   *
   * Links this error to the specific upload operation for debugging
   * and user feedback.
   *
   * @example
   * '550e8400-e29b-41d4-a716-446655440000'
   */
  correlationId: string;
};

// ============================================================================
// NSD Upload Stage Enum
// ============================================================================

/**
 * Processing stages for NSD document upload operations.
 *
 * Represents the sequential phases of document processing from
 * initial read through validation completion.
 *
 * @example
 * const stage: NSDUploadStage = 'parsing';
 */
export enum NSDUploadStage {
  /**
   * Reading file from disk or receiving text content.
   *
   * First stage where the document is loaded into memory.
   */
  READING = 'reading',

  /**
   * Parsing markdown structure and extracting sections.
   *
   * Second stage where markdown is analyzed for structure.
   */
  PARSING = 'parsing',

  /**
   * Identifying and extracting individual scenes.
   *
   * Third stage where scene boundaries are detected and content extracted.
   */
  EXTRACTING = 'extracting',

  /**
   * Validating document structure and required fields.
   *
   * Fourth stage where the parsed document is validated for completeness.
   */
  VALIDATING = 'validating',

  /**
   * All processing finished successfully.
   *
   * Final stage indicating the upload operation is complete.
   */
  COMPLETE = 'complete',
}

// ============================================================================
// NSD Domain Entity DTOs
// ============================================================================

/**
 * Data Transfer Object for NSD (Narrative Scene Document) entities.
 *
 * Represents a complete NSD document with metadata, content, and
 * extracted scenes. Used for serialization across IPC boundaries.
 *
 * @example
 * const document: NSDDocumentDTO = {
 *   id: 'nsd-doc-123',
 *   fileName: 'quest-01-tavern-contract.md',
 *   questName: 'The Tavern Contract',
 *   content: '# Quest 01: The Tavern Contract\n\n## Scene 1...',
 *   metadata: {
 *     title: 'Quest 01: The Tavern Contract',
 *     status: 'draft',
 *     campaignImportance: 'main',
 *     narrativeArc: 'introduction'
 *   },
 *   scenes: [
 *     { id: 'scene-1', title: 'Meeting at Tavern', sceneNumber: 1, ... }
 *   ]
 * };
 */
export interface NSDDocumentDTO {
  /**
   * Unique identifier for the NSD document.
   *
   * Generated by the system and used for internal references.
   *
   * @example
   * 'nsd-doc-123'
   */
  id: string;

  /**
   * Original filename of the uploaded NSD document.
   *
   * Preserved from the upload for display and identification.
   *
   * @example
   * 'quest-01-tavern-contract.md'
   */
  fileName: string;

  /**
   * Human-readable quest name extracted from the document.
   *
   * Typically the main heading or title from the NSD markdown.
   *
   * @example
   * 'The Tavern Contract'
   * @example
   * 'Quest 01: Bard\'s Revelation'
   */
  questName: string;

  /**
   * Full markdown content of the NSD document.
   *
   * Original text content preserved for reference and re-parsing.
   *
   * @example
   * '# Quest 01: The Tavern Contract\n\n## Scene 1: Meeting...\n\nScene content...'
   */
  content: string;

  /**
   * Structured metadata extracted from the NSD document.
   *
   * Contains quest attributes like status, importance, narrative position,
   * and other categorization information.
   *
   * @example
   * {
   *   title: 'Quest 01: The Tavern Contract',
   *   status: 'draft',
   *   campaignImportance: 'main',
   *   narrativeArc: 'introduction',
   *   estimatedDuration: 'short',
   *   recommendedLevel: 1,
   *   questGiver: 'Tavern Keeper',
   *   rewards: ['gold:100', 'exp:50']
   * }
   */
  metadata: NSDMetadata;

  /**
   * List of scenes extracted from the NSD document.
   *
   * Ordered by appearance in the document, each scene contains
   * title, content, scene number, and optional summary.
   *
   * @example
   * [
   *   { id: 'scene-1', title: 'Tavern Meeting', sceneNumber: 1, content: '...', summary: '...' },
   *   { id: 'scene-2', title: 'Bard Conversation', sceneNumber: 2, content: '...' }
   * ]
   */
  scenes: NSDSceneDTO[];
}

/**
 * Data Transfer Object for individual NSD scenes.
 *
 * Represents a single narrative scene extracted from an NSD document,
 * containing all information needed for prompt generation.
 *
 * @example
 * const scene: NSDSceneDTO = {
 *   id: 'scene-1',
 *   title: 'Tavern Meeting',
 *   content: 'The hero enters the tavern. The keeper waves...',
 *   sceneNumber: 1,
 *   summary: 'Introduction to quest giver and initial contract offer'
 * };
 */
export interface NSDSceneDTO {
  /**
   * Unique identifier for this scene within the document.
   *
   * Scoped to the parent document, not globally unique.
   *
   * @example
   * 'scene-1'
   * @example
   * 'nsd-doc-123-scene-5'
   */
  id: string;

  /**
   * Human-readable title for the scene.
   *
   * Extracted from the scene heading in the NSD markdown.
   *
   * @example
   * 'Tavern Meeting'
   * @example
   * 'Bard\'s Revelation'
   */
  title: string;

  /**
   * Full narrative content of the scene.
   *
   * Contains the complete scene description, dialogue, and action
   * as written in the NSD document.
   *
   * @example
   * 'The hero enters the dimly lit tavern. Smoke hangs in the air...'
   */
  content: string;

  /**
   * Sequential number indicating scene order in the document.
   *
   * 1-based index matching the scene's position in the narrative flow.
   *
   * @example
   * 1 (first scene)
   * @example
   * 3 (third scene)
   */
  sceneNumber: number;

  /**
   * Optional brief summary of the scene.
   *
   * Provides a high-level overview of the scene's purpose and key events.
   * May be omitted if not present in the NSD document.
   *
   * @example
   * 'Introduction to quest giver and initial contract offer'
   * @example
   * 'Hero learns about the ancient artifact from the bard'
   */
  summary?: string;
}

/**
 * Structured metadata extracted from NSD documents.
 *
 * Contains categorization and classification information about
 * the quest/narrative described in the NSD document.
 *
 * @example
 * const metadata: NSDMetadata = {
 *   title: 'Quest 01: The Tavern Contract',
 *   status: 'draft',
 *   campaignImportance: 'main',
 *   narrativeArc: 'introduction',
 *   estimatedDuration: 'short',
 *   recommendedLevel: 1,
 *   questGiver: 'Tavern Keeper',
 *   rewards: ['gold:100', 'exp:50']
 * };
 */
export interface NSDMetadata {
  /**
   * Full title of the quest or narrative.
   *
   * Main heading or title from the NSD document.
   *
   * @example
   * 'Quest 01: The Tavern Contract'
   */
  title: string;

  /**
   * Current status of the quest/narrative.
   *
   * Indicates the development or completion state.
   *
   * - `draft`: Initial draft, not yet implemented
   * - `review`: Under review for implementation
   * - `approved`: Approved for implementation
   * - `implemented`: Implemented in the game
   * - `testing`: Implemented and being tested
   * - `complete`: Fully implemented and tested
   *
   * @example
   * 'draft'
   * @example
   * 'implemented'
   */
  status: 'draft' | 'review' | 'approved' | 'implemented' | 'testing' | 'complete';

  /**
   * Importance of this quest to the main campaign.
   *
   * Indicates narrative priority and player impact.
   *
   * - `main`: Critical to main storyline completion
   * - `side`: Optional content, enriches world but not required
   * - `hidden`: Secret/hidden quest, discovery-based
   *
   * @example
   * 'main'
   * @example
   * 'side'
   */
  campaignImportance: 'main' | 'side' | 'hidden';

  /**
   * Position of this quest in the narrative arc.
   *
   * Indicates where this quest fits in the story structure.
   *
   * - `introduction`: Introduces characters, setting, or main conflict
   * - `rising`: Builds tension and develops the plot
   * - `climax`: Peak of dramatic tension or conflict
   * - `falling`: Resolves immediate conflicts, leads to conclusion
   * - `resolution`: Ties up loose ends, provides closure
   * - `standalone`: Independent quest not part of larger arc
   *
   * @example
   * 'introduction'
   * @example
   * 'climax'
   */
  narrativeArc: 'introduction' | 'rising' | 'climax' | 'falling' | 'resolution' | 'standalone';

  /**
   * Estimated duration to complete this quest.
   *
   * Rough time estimate for players to finish the quest.
   *
   * - `short`: Under 30 minutes
   * - `medium`: 30 minutes to 2 hours
   * - `long`: 2 hours to 5 hours
   * - `epic`: Over 5 hours (multi-session quest)
   *
   * @example
   * 'short'
   * @example
   * 'medium'
   */
  estimatedDuration?: 'short' | 'medium' | 'long' | 'epic';

  /**
   * Recommended character level for this quest.
   *
   * Suggests appropriate level range for balance and difficulty.
   *
   * @example
   * 1 (starting quest)
   * @example
   * 15 (mid-game quest)
   */
  recommendedLevel?: number;

  /**
   * Name or identifier of the quest giver NPC.
   *
   * The character who assigns or initiates the quest.
   *
   * @example
   * 'Tavern Keeper'
   * @example
   * 'Bard Elara'
   */
  questGiver?: string;

  /**
   * List of rewards for completing this quest.
   *
   * Strings describing rewards in various formats.
   * Common formats: 'gold:N', 'exp:N', 'item:ItemName'
   *
   * @example
   * ['gold:100', 'exp:50', 'item:Health Potion']
   * @example
   * ['gold:500', 'skill:Bargain']
   */
  rewards?: string[];
}

/**
 * Validation error detail for NSD document processing.
 *
 * Represents a specific validation error found during document
 * parsing or validation, with optional additional details.
 *
 * @example
 * const error: NSDValidationError = {
 *   code: 'MISSING_REQUIRED_FIELD',
 *   message: 'Required field "title" is missing from document metadata',
 *   details: { field: 'title', location: 'metadata section' }
 * };
 */
export interface NSDValidationError {
  /**
   * Machine-readable error code for categorization.
   *
   * Standard validation error codes:
   * - `MISSING_REQUIRED_FIELD`: Required field not found
   * - `INVALID_FORMAT`: Field format doesn't match expected pattern
   * - `SCENE_NUMBER_CONFLICT`: Duplicate or conflicting scene numbers
   * - `METADATA_INCOMPLETE`: Required metadata fields missing
   * - `CONTENT_TOO_SHORT`: Scene or document content insufficient
   * - `EMPTY_DOCUMENT`: Document contains no content
   *
   * @example
   * 'MISSING_REQUIRED_FIELD'
   * @example
   * 'SCENE_NUMBER_CONFLICT'
   */
  code: string;

  /**
   * Human-readable error message.
   *
   * Clear description of the validation issue and how to fix it.
   *
   * @example
   * 'Required field "title" is missing from document metadata'
   * @example
   * 'Scene numbers 3 and 4 are both assigned to "Throne Room"'
   */
  message: string;

  /**
   * Optional additional context about the error.
   *
   * Provides structured details for debugging or fixing the issue.
   * May include field names, locations, expected values, etc.
   *
   * @example
   * { field: 'title', location: 'metadata section', expected: 'string' }
   * @example
   * { conflict: ['scene-3', 'scene-4'], bothAssignedTo: 'Throne Room' }
   */
  details?: Record<string, unknown>;
}
